apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitnami-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitnami-nginx
  targetNamespace: default
